src/combinator/sample.js
src/index.js
test/combinator/sample-test.js

Close #9 
Port sample from @most/sample.  Remove older sample API and tests.

Port sample from @most/sample

---

src/index.js

🤦‍♂️ Enforcing index's own types upon itself would have prevented this.  I'll see if that is easy to do.

fix(core): Fix newDefaultScheduler argument order

---

src/combinator/delay.js
src/combinator/errors.js
src/combinator/limit.js
src/combinator/scan.js
src/index.js
src/index.js.flow
src/scheduler/PropagateTask.js
src/source/core.js
src/source/fromArray.js
src/source/fromIterable.js
src/source/periodic.js
test/helper/testEnv.js

Remove the need to use thisArg in PropagateTask run functions by passing the task as an additional arg.  This also moves PropagateTask helpers from static methods to plain functions and switches PropagateTask to use named exports.  Convert touched sources to ES2015.
Close #19
ISSUES CLOSED: #19

feat(core): Add task arg to PropagateTask run function

---

type-definitions/PropagateTask.d.ts
type-definitions/combinator/zip.d.ts
type-definitions/types.d.ts

Fix some basic compiler errors that occur just by trying to use `@most/core` with typescript.

chore(type-definitions): fix compiler errors

---

packages/core/src/index.js.flow
packages/core/src/source/newStream.js
packages/core/test/combinator/chain-test.js
packages/core/test/combinator/concatMap-test.js
packages/core/test/combinator/continueWith-test.js
packages/core/test/combinator/errors-test.js
packages/core/test/combinator/mergeConcurrently-test.js
packages/core/test/helper/observe.js
packages/core/test/helper/reduce.js
packages/core/test/helper/stream-helper.js
packages/core/test/newStream-test.js
packages/core/test/observe-test.js
packages/core/test/source/generate-test.js
packages/core/test/source/iterate-test.js
packages/core/test/source/unfold-test.js
packages/core/type-definitions/most.d.ts
packages/core/type-definitions/scheduler.d.ts
packages/core/type-definitions/source/newStream.d.ts

This adds a trivial constructor to make a stream from a `Sink -> Scheduler -> Disposable` function, which is all a stream is anyway now that #45 has been merged.  While someone *can* just make an object with a run() *method*, this feels a reasonable API to help folks.  It doesn't add any additional footgunnery beyond object-with-run-method, afaict, though it may encourage folks to try to write more imperative push streams ... maybe that's solvable via documentation?

Add newStream

---

packages/core/.flowconfig
packages/core/src/combinator/withArrayValues.js
packages/core/src/index.js
packages/core/src/index.js.flow
packages/core/test/combinator/withArrayValues-test.js
packages/core/type-definitions/combinator/withArrayValues.d.ts
packages/core/type-definitions/most.d.ts

This adds `withArrayValues` and `zipArrayValues` for mapping values from an array onto a stream.  In the case of `withArrayValues`, for each event, the stream provides the time component, and the array provides the value component.  Similarly for `zipArrayValues`, except it accepts a function to compute the value component from the array value and incoming event value.
- Run flow on the whole test dir.  It will only check files with `@flow` at the top, which for now, is only the new `withArrayValues-test.js`.  But, I like the idea of using unit tests also to check types.  Feedback welcome 😄 
- Note that to do this, I had to give flow visibility into the top-level `node_modules` folder, since lerna is hoisting common dependencies (such as `mocha` and `@briancavalier/assert`) to the top …

feat(withArrayValues): Add withArrayValues and zipArrayValues

---

packages/scheduler/src/clock.js
packages/scheduler/src/index.js.flow
packages/scheduler/test/clock-test.js
packages/scheduler/type-definitions/index.d.ts

Fix #69 
Close #71 
Consider `Date` and `performance` to be acceptable `Clock` types.   Add new RelativeClock that accepts any `Clock` and creates a new `Clock` relative to its current time.

fix(clock): Call performance.now as a method. Add new RelativeClock

---

packages/core/src/combinator/continueWith.js
packages/core/src/combinator/errors.js
packages/core/src/combinator/mergeConcurrently.js
packages/core/src/combinator/switch.js
packages/core/src/scheduler/runWithLocalTime.js
packages/core/src/sink/RelativeSink.js
packages/scheduler/.flowconfig
packages/scheduler/src/AbstractScheduler.js
packages/scheduler/src/RelativeScheduler.js
packages/scheduler/src/ScheduledTask.js
packages/scheduler/src/Scheduler.js
packages/scheduler/src/index.js
packages/scheduler/src/index.js.flow
packages/scheduler/src/relative.js
packages/scheduler/src/schedule.js
packages/scheduler/test/AbstractScheduler-test.js
packages/scheduler/test/RelativeScheduler-test.js
packages/scheduler/test/helper/FakeScheduler.js
packages/scheduler/test/helper/FakeTask.js
packages/scheduler/test/relative-test.js
packages/scheduler/test/schedule-test.js
packages/scheduler/type-definitions/index.d.ts
packages/types/index.d.ts
packages/types/index.js.flow

This PR switches to stream-local time.  Each stream effectively has its own virtual clock that starts at zero.  In reality, they all share the same clock, but have an associated origin time offset.  This is done via a simple RelativeScheduler that wraps Scheduler and adds an offset.  Higher-order streams create a new RelativeScheduler, based on their own scheduler, with the appropriate time offset, and use that to run each inner stream.
Time must also be transformed "in the other direction", from local time to outer time, when merging inner events back to the outer sink.  RelativeSink implements that transform.  It was also convenient to implement it directly in the custom sinks used by mergeConcurrently and switchLatest.  It might be better to take the hit on creating a new extra …

feat(core): Add stream local time

---

packages/core/src/index.js

newStream declared in TypeScript defs but not matched by an actual export.

fix(newStream): export newStream from index.js

---

packages/prelude/package.json

During the most recent `lerna publish`, I selected patch version bump for `@most/prelude` and minor version bump for all others.  However, lerna still bumped the minor version when publishing `@most/prelude`.
This seems like a lerna bug, and I'll work on reporting it.  In the meantime, this PR updates `@most/prelude`'s package.json version to match [what is actually published in npm, 1.6.0](https://www.npmjs.com/package/@most/prelude).

fix(package.json): make package.json version match npm

---

packages/core/src/scheduler/runWithLocalTime.js

Accumulate RelativeSink offsets to avoid nesting.
I don't like `instanceof`, but in this case it feels like the right thing.  The alternative would be to require a new method (i.e. analogous to Scheduler's recently-added `relative` method) on all Sinks, which feels too annoying for people writing custom Sinks.  Alternatively, we could offer a superclass that provides the method, but I dislike coupling people's code to a superclass even more than I dislike `instanceof`.

feat(runWithLocalTime): avoid nesting RelativeSinks

---

.gitignore
packages/core/package.json
packages/disposable/package.json
packages/prelude/package.json
packages/scheduler/package.json
packages/types/package.json

Coverage was enabled in `@most/prelude`, but not other packages.  This adds coverage reporting to the rest of the packages and updates nyc to the latest version.

chore(coverage): Enable nyc coverage in all packages

---

packages/scheduler/src/index.js.flow
packages/types/index.js.flow

It seems like this should be fine, since all the types line up visually.
```js
class NullSink {
event (t: Time, x: any): void {}
end (t: Time): void {}
error (t: Time, e: Error): void {}
}
const nullSink: Sink<any> = new NullSink()
```
It isn't.  Flow considers object properties to be _invariant_ by default (See [Property Invariance here](https://flow.org/blog/2016/10/04/Property-Variance/). I'm still not sure exactly _why_ prototype properties violate the invariance rule, but they do:
```
src/split.js:16
16: const nullSink: Sink<any> = new NullSink()
^^^^^^^^^^^^^^ NullSink. Covariant property `error` incompatible with invariant use in
16: const nullSink: Sink<any> = new NullSink()
^^^^^^^^^ object type
```
This PR adds explicit covariance for the properties of core types, to allow …

feat(types): Add explicit covariance to allow custom types

---

packages/core/src/index.js

The type definitions were exporting `at`, but it was missing from the actual JS exports.  This PR adds it to the JS exports.

fix(at): export at

---

docs/api.rst
packages/core/src/index.js

Add skipAfter to JS exports.  The types were there, but the function wasn't exported.  Added a doc reminder, too.

fix(skipAfter): export skipAfter

---

packages/core/src/index.js.flow
packages/core/src/scheduler/PropagateTask.js
packages/core/type-definitions/PropagateTask.d.ts

AFAICT, the only usage of this was in `fromArray` and `fromIterable`.  Since those were removed, I think we can stop passing the task itself (which was always kind of a hack, anyway) to the run function.

refactor(PropagateTask): remove now-unused  arg from PropagateTaskRun

---

packages/core/src/combinator/slice.js
packages/core/src/disposable/SettableDisposable.js
packages/core/test/disposable/SettableDisposable-test.js

Port fix from cujojs/most#468, simplify SettableDisposable.  SettableDisposable was a straggler and still used promises.  This removes the promise usage.  One slightly odd thing, is that this makes the timing of the underlying disposal invisible.  That's probably fine, but let me know if you see any potential problems with it.

fix(slice): Port fix from cujojs/most#468, simplify SettableDisposable

---

packages/core/src/combinator/limit.js
packages/core/test/limit-test.js

Ported from https://github.com/cujojs/most/pull/472
It looks like there was also a bug in the DebounceSink constructor.  It wasn't correct to use disposeBoth, since the DebounceSink instance is already the disposable that is being returned from run().

fix(debounce): ensure debounce disposes source

---

docs/api.rst
docs/concepts.rst
packages/scheduler/src/index.js.flow
packages/scheduler/type-definitions/index.d.ts
packages/types/index.d.ts
packages/types/index.js.flow

The goal of this PR is to add documentation for:
1. all packages except `@most/prelude` (I'm imagining a separate PR for that)
2. the core types
3. as much of the info in the [Architecture wiki](https://github.com/cujojs/most/wiki/Architecture) that makes sense in the current structure
* I'd rather not hold up this PR to try to integrate all of the Architecture info.  We can discuss and do that in another PR.

docs(api): Expand API docs

---

packages/core/src/index.js.flow
packages/core/type-definitions/PropagateTask.d.ts

Without this change, propagateTask can't be used to pass a wrapper object as the value, with the internal values then unwrapped by the task runner for delivery to the sink.

fix(types): propagateTask; decouple value type from sink type

---

docs/README.md

Just a convenient link to the readthedocs site.

Add minimal README to docs directory

---

examples/counter/.flowconfig
examples/counter/index.html
examples/counter/package-lock.json
examples/counter/package.json
examples/counter/rollup.config.js
examples/counter/src/index.js

I figured I'd get the ball rolling on adding some examples.  This is the usual, trivial inc/dec counter.  It's probably more important to discuss:
1. Is this the right place to put examples?
2. Is the structure of the example reasonable? i.e. it's very self-contained, with it's own package.json, package-lock.json, and rollup.config.js.  Another option may be to share those one level up in the examples folder, as we've done in [mostjs/examples](https://github.com/mostjs/examples).  Might be easier maintenance if we do.

feat(examples): Add simple example counter

---

packages/core/package.json
packages/core/rollup.config.js
packages/disposable/package.json
packages/disposable/rollup.config.js
packages/scheduler/package.json
packages/scheduler/rollup.config.js

In the same vein as https://github.com/mostjs/hold/pull/22, this stops bundling deps into each package.  Without this change, for example, we end up with a copy of `@most/prelude` functions in `@most/core`, `@most/disposable`, and `@most/scheduler`.  An application that uses `@most/core` would ultimately end up with 3 copies of some `@most/prelude` functions!  I verified this using the example in #139.  In that tiny example, it reduced the (unminified and non-gzipped) size by 10k.  Perhaps more importantly, it ended up with no duplicate functions.

chore(build): stop bundling deps into builds

---

docs/api.rst
docs/concepts.rst

Add some info on finite and infinite streams, and attempt to clarify stream failures vs. application errors.  Docs for `periodic` were missing, so I added them along the way.
I also fixed some sphinx errors.  It seems to get confused when you have a `:ref:` or inline code/preformatted span that *isn't immediately surrounded by spaces*.  For example, these are problematic:
```rst
Some :ref:`Stream`s blah blah
Some ``Stream``s blah blah
```
I don't have a good solution to the second one.  The first one can be solved by using the explicit text+reference syntax:
```rst
Some :ref:`Streams <Stream>`
```

docs(concepts): Add finite, infinite, failed stream info, periodic docs

---

packages/core/src/combinator/slice.js
packages/core/src/source/empty.js
packages/core/test/slice-test.js
packages/core/test/source/empty-test.js

See #150, specifically the "Make slice fusion smarter about empty()" section.
This PR improves detection of empty slices.  If slice detects that it has reached the point where it could only return an empty stream, it will return canonical `empty()`.  Specifically, it now detects these cases _recursively_:
* when it computes end <= start
* when it encounters canonical `empty()`

feat(slice): improve empty slice detection

---

packages/core/src/combinator/zipItems.js
packages/core/test/combinator/zipItems-test.js

Use take(array.length) to remove duplicate logic in ZipArrayValuesSink
Fix: #147

fix: simplify ZipArrayValuesSink logic

---

docs/index.rst

I think these were auto-generated or existed in whatever template I started with, but they're broken.  You can try them [here](http://mostcore.readthedocs.io/en/latest/index.html#indices-and-tables).

Remove links to non-existent pages

---

packages/core/src/combinator/snapshot.js

The sample combinator was taking values from the sampler stream instead of the values stream

Correct the order of arguments in the sample combinator

---

packages/core/src/combinator/snapshot.js
packages/core/test/combinator/snapshot-test.js

Close #185 
If either the values or sampler is canonical empty, return canonical empty.  Add canonical empty tests, and sample tests, including test for the bug fixed by #184.

Return canonical empty from snapshot and sample

---

docs/api.rst

The order of the parameters of `ap` was reversed in the docs.

Fix order of ap parameters

---

packages/disposable/src/disposeAll.js
packages/disposable/src/disposeNone.js
packages/disposable/test/disposeAll-test.js
packages/disposable/test/disposeNone-test.js

Add disposable fusion for disposeAll and disposeNone.
This allows disposeAll to:
1. filter out disposeNone
2. return disposeNone if after filtering out disposeNone, it ends up with an array of length zero.  This has the additional benefit of making `disposeAll([])` return disposeNone.
3. recognize nested disposeAll, and flatten them into a single array, also recursively applying 1 and 2.  This will flatten an entire tree of disposables as far as possible by flattening arrays and removing disposeNone.
See also #216

Add disposable fusion

---

packages/core/test/helper/reduce.js

while working on `@most/test` I found an error on this function. Thankfully it did not affect the validity of the tests. This solves two problems:
- Promise always returned `undefined` instead of the final value
- If the initial value was a primitive (ie. not passed by reference) the result would be the initial value

fix for reduce helper test function

---

packages/core/.flowconfig
packages/core/src/index.js.flow
packages/core/test/flow/combinator/merge.js
packages/core/type-definitions/combinator/merge.d.ts

As per recent discussion, this loosens the type of the 2-stream `merge` to accept streams of different types and produce a stream of the union.
At first, this might seem unsafe because you might accidentally call merge with different types, say `A` and `B` when you didn't mean to.  However, since the resulting stream has a union type, `A | B`, when you try to use it, for example by mapping it with a function `A => C`, the type checker will prevent it.  Thus, I believe this is entirely safe, while adding some flexibility for situations where you might actually want to construct a union.

Allow merge to produce union

---

docs/api.rst

Follow up to #224, which didn't include the doc update.

Update merge docs to show union return type

---

docs/concepts.rst

There was some discussion about this recently on gitter, and I figured I'd try to add a bit more info.  The docs do mention the async guarantee, but don't provide any details about why it matters, so I figured I'd add some.

Add more info about Stream run() async guarantee

---

docs/faq.rst
docs/getting-started.rst
docs/index.rst
docs/upgrading-guide.rst

Add a simple Getting Started section with install instructions, links to examples, and link to stub doc for upgrading from most 1.x.  My intent is to get something simple in place that we can expand as necessary.  The upgrading doc is just a stub, but gives us a place to start writing.

Add getting started section

---

docs/api.rst

See https://github.com/cujojs/most/issues/524
Document the behavior when awaitPromises encounters a forever pending promise.  This behavior is implied in the existing documentation, in that event order is preserved.  However, it may not be obvious to some that preserving order implies that a forever-pending promise will prevent all subsequent events.  This PR adds an explicit section that hopefully will help to make it clear.

Add await promise pending forever note

---

docs/api.rst
packages/scheduler/src/clock.js

Since, [`performance.now` is ubiquitous](https://caniuse.com/#search=performance.now), we can deprecate the Date-based clock, which wasn't monotonic to begin with.

Deprecate newDateClock

---

docs/api.rst

See #266
`run` returns `Disposable`.  It's correct in code and type definitions, but was incorrectly documented as `void` in the API docs.  This fixes the docs and adds a note to emphasize `@most/core`'s declarative approach, and to provide guidance on use cases where `run` and it's returned `Disposable` may be necessary.

Fix run docs return type, add note about declarative vs imperative

---

packages/core/src/combinator/timeslice.js
packages/core/test/timeslice-test.js
packages/scheduler/src/ScheduledTask.js
packages/scheduler/src/Timeline.js

See [this comment](https://github.com/mostjs/core/issues/266#issuecomment-459485449) for an example of the bug.  It's a subtle interaction between `run` and `until`.
This PR fixes the bug.
Naively fixing the bug introduced a race between disposables.  SettableDisposable is the standard way to break disposable races in a controlled way, and it worked well here.
Looking at `since` and `until` with fresh eyes, it also seemed they could be simplified.  So, I did.  I also made Timeline slightly more aggressive in freeing its internal data structures when it knows it has an empty time slot.

Simplify until/since and fix subtle until dispose bug

---

examples/most-redis-docker/.gitignore
examples/most-redis-docker/Dockerfile
examples/most-redis-docker/README.md
examples/most-redis-docker/config.js
examples/most-redis-docker/consume.js
examples/most-redis-docker/docker-compose.yml
examples/most-redis-docker/package-lock.json
examples/most-redis-docker/package.json
examples/most-redis-docker/publish.js
examples/most-redis-docker/redis.js

I think it's hard to provide an example that is easy to run and is also somewhat close to a "real world" scenario.  By allowing users to run this example by installing docker _or_ installing redis, I hope to make it a bit easier.  
I'm very open to suggestions and improvements:  coding style, README contents, variable names, etc.  
Honestly, composing the most.js streams felt clunky without formal function composition tools.  Am I doing it right?  Could I do it better?

Add most-redis-docker example.

---

packages/core/src/combinator/switch.js
packages/core/test/switch-test.js

This fixes https://github.com/mostjs/core/issues/284.
I confirmed that the original `switchLatest` emits an error event with time `2`, which should be `1`, and removing ` + this.min` from `Segment#_dispose` resolves the issue.
To be honest, I find my way of writing test case pretty clumsy, but I could not find a  straightforward way to examine the case.
Feel free to request changes, I'll appreciate it.
Thank you.

Fix duplicate addition of offset time on switchLatest

---

docs/api.rst
packages/core/src/index.js.flow
packages/core/test/flow/combinator/mergeArray.js
packages/core/type-definitions/combinator/combine.d.ts
packages/core/type-definitions/combinator/merge.d.ts
packages/core/type-definitions/combinator/variadic.d.ts
packages/core/type-definitions/combinator/zip.d.ts

This uses a variation of the technique from [Simpler Variadic Function Types in Typescript](https://gist.github.com/briancavalier/62f784e20e4fffc4d671126b7f91bad0) to improve the types of zipArray and combineArray for TS, allowing them to scale to any arity.
It also improves the type of mergeArray, allowing it to be heterogeneous while remaining strongly typed.  Essentially, this extends the union behavior of `merge` to arbitrary arrays of streams.  This works by leveraging the fact that TS union types obey a distributive law.
In general, I see strong heterogeneous types as a plus.  However, there could be a couple downsides:
1. They could be surprising or confusing for some users.
2. I haven't found any way to achieve parity in Flow.  What are the implications for documentation?

Apply new technique for strong heterogenous array types

---

packages/core/src/index.js.flow
packages/core/test/flow/combinator/mergeConcurrently.js

Fix #289 
This fixes parameter ordering to match the implementation (the first two params were reversed), and applies correctly represents currying for the 1-2 and 1-1-1 variants.  Flow type tests included.

Fix mergeMapConcurrently flow type

---

packages/core/type-definitions/combinator/mergeConcurrently.d.ts

`mergeMapConcurrently` seems to be missing its type definition.
I have checked that copying-and-pasting these definitions into my project's `node_modules/@most/core/type-definitions/combinator/mergeConcurrently.d.ts` seemed suggest types as documented, but not tested seriously.

Add `mergeMapConcurrently` type definition

---

packages/core/test/perf/README.md
packages/core/test/perf/chain.js
packages/core/test/perf/concatMap.js
packages/core/test/perf/filter-map-reduce.js
packages/core/test/perf/merge-nested.js
packages/core/test/perf/merge.js
packages/core/test/perf/package-lock.json
packages/core/test/perf/package.json
packages/core/test/perf/runners.js
packages/core/test/perf/scan.js
packages/core/test/perf/skipRepeats.js
packages/core/test/perf/slice.js
packages/core/test/perf/switch.js
packages/core/test/perf/zip.js

* Add RxJS 6 using recommended `pipe` coding style.
* Remove RxJS 4 and 5.
* Update perf test code style to align more closely with the rest of the repo (still not fully aligned, tho).

Update perf tests

---

packages/core/type-definitions/combinator/filter.d.ts

Hi, this PR adds support for type refinements in filter operator:
```typescript
type Foo = { foo: string }
const isFoo = (obj: any): obj is Foo => typeof obj['foo'] === 'string';
declare const source: Stream<unknown>;
const foo = filter(isFoo)(source) // Stream<Foo>
```

feat(core): support refinements in filter operator

---

packages/disposable/test/disposeAll-test.ts

This should fix the error in https://github.com/mostjs/core/pull/313 by being forward compatible with sinon 7.5.1.  It's also compatible with the version on current master.

Fix sinon spy function type

---

docs/api.rst
packages/core/src/combinator/continueWith.ts
packages/core/src/combinator/errors.ts
packages/core/src/index.js.flow
packages/core/src/index.ts
packages/core/test/combinator/continueWith-test.ts
packages/core/test/combinator/errors-test.ts

This ports https://github.com/cujojs/most/pull/531 to `@most/core`, and extends it to cover `continueWith` as well.
Specifically looking for feedback on the `continueWith` change before I proceed with tests and docs.

Allow union return type for recoverWith and continueWith

---

.circleci/config.yml
README.md

Just a workaround adding `--legacy-peer-deps`.
Actually, I have really no idea why npm complains that some dependencies in the monorepo do no longer fit together…

fixes CI build, some remarks for installing deps in local repo
