- test/perf/chain.js
- test/perf/concatMap.js
- test/perf/filter-map-reduce.js
- test/perf/merge-nested.js
- test/perf/merge.js
- test/perf/scan.js
- test/perf/skipRepeats.js
- test/perf/slice.js
- test/perf/switch.js
- test/perf/zip.js
Since we decided to remove `from` in favor of explicit `fromArray` et al.
> Update perf tests to use fromArray

- src/disposable/Disposable.js
- src/disposable/MemoizedDisposable.js
- src/disposable/SettableDisposable.js
- src/disposable/dispose.js
- src/disposable/disposeSafely.js
- src/scheduler/ClockTimer.js
Mostly just cleanup and conversion to ES.
> Update and simplify disposables

- .travis.yml
- northbrook.js
- package.json
Adds a simple northbrook configuration to use eslint and rollup plugins.
> chore(META): add basic configurations for northbrook

- src/index.js.flow
> fix(flow): Add missing generate() type

- package.json
- test/observe-test.js
> chore(test): Switch 1 existing mocha test to use @briancavalier/assert

- test/disposable/Disposable-test.js
- test/disposable/SettableDisposable-test.js
- test/disposable/dispose-test.js
- test/sink/SafeSink-test.js
convert disposable tests to mocha + @briancavalier/assert
convert sink tests to mocha + @briancavalier/assert
> test(disposable): convert sink & disposable tests

- packages/core/test/combinator/applicative-test.js
- packages/core/test/combinator/chain-test.js
- packages/core/test/combinator/concatMap-test.js
- packages/core/test/combinator/continueWith-test.js
- packages/core/test/combinator/errors-test.js
- packages/core/test/combinator/loop-test.js
- packages/core/test/combinator/merge-test.js
- packages/core/test/combinator/mergeConcurrently-test.js
- packages/core/test/combinator/promises-test.js
- packages/core/test/combinator/sample-test.js
- packages/core/test/combinator/scan-test.js
- packages/core/test/helper/FakeDisposeSource.js
- packages/core/test/helper/VirtualTimer.js
- packages/core/test/helper/stream-helper.js
- packages/core/test/helper/testEnv.js
convert combinator tests to mocha + @briancavalier/assert
closes #37
> test(combinator) convert combinator tests

- README.md
> docs(README): fix example

- packages/core/package.json
Remove buster as it's no longer needed.  All tests ported to mocha.
> chore(package): Remove buster dep

- packages/core/src/combinator/slice.js
Port fix from https://github.com/cujojs/most/pull/428
> fix(take): Prevent take and takeWhile from disposing twice

- packages/core/src/combinator/slice.js
- packages/core/src/index.js.flow
- packages/core/test/slice-test.js
- packages/core/type-definitions/combinator/slice.d.ts
Port @davidchase's `skipAfter` implementation and tests from cujojs/most#429 and cujojs/most#431
> feat(skipAfter): port skipAfter from cujojs/most

- README.md
There were some missing imports too.
> Update example in readme to the newer scheduler API

- docs/api.rst
Add minimal docs for some functions, starting with runEffects, and stream creation.
> docs(api): Add docs for a few sources

- docs/api.rst
Make some reST and consistency fixes as well.
> docs(api): Add propagatetask docs

- docs/api.rst
Just "style" changes/fixes and for `throwError` i switched the code block with the description to be consistent with the rest
I think `sample` may need some docs, i can add it to here or send in another PR
> docs(api): minor fixes

- docs/api.rst
- concatMap
- mergeConcurrently
- mergeMapConcurrently
- switchLatest
> docs(api): add missing documentation

- package.json
- packages/core/.flowconfig
- packages/scheduler/.flowconfig
Update to official lerna 2.0.0 release.
I encountered a new flow error when updating, not sure why.  Maybe this version of lerna includes a new dep on conventional-changelog:
```
lerna ERR! execute > flow check
lerna ERR! execute
lerna ERR! execute Error: ../../node_modules/conventional-changelog-core/test/fixtures/_malformation.json:1
lerna ERR! execute   1:
lerna ERR! execute      ^ Unexpected end of input
lerna ERR! execute
lerna ERR! execute
lerna ERR! execute Found 1 error
```
So, I had to ignore it in the flow config.
> chore(lerna): update lerna to 2.0.0. Ignore problematic files

- packages/disposable/src/disposeAll.js
- packages/disposable/src/disposeWith.js
- packages/disposable/src/index.js.flow
- packages/disposable/src/tryDispose.js
- packages/disposable/type-definitions/index.d.ts
Curry arity > 1 `@most/disposable` api functions.
> feat(disposable): curry API

- .travis.yml
(Ok, no merge commit this time.  I guess it was because my local master was 1 commit behind origin/master)
> chore(ci): stop testing on node 4, to avoid npm 2

- packages/core/src/index.js.flow
> fix(types): fix continueWith flow types

- docs/api.rst
- packages/disposable/src/dispose.js
- packages/disposable/src/disposeAll.js
- packages/disposable/src/disposeOnce.js
- packages/disposable/src/disposeWith.js
- packages/disposable/src/index.js
- packages/disposable/src/index.js.flow
- packages/disposable/test/dispose-test.js
- packages/disposable/type-definitions/index.d.ts
Also, fix TS defs for `@most/disposable`
> feat(disposable): Add dispose function

- docs/api.rst
Unify style and language while correcting various grammar, typos, and spelling.
> Correct grammar, typos, spelling, and formatting

- examples/counter/package-lock.json
- examples/counter/package.json
> chore(examples): update example deps

- docs/faq.rst
- docs/index.rst
See #155
I figured I'd get the ball rolling.
> docs(FAQ): start FAQ

- docs/concepts.rst
Close #160
Signed-off-by: Frederik Krautwald <fkrautwald@gmail.com>
> Reword Source and sink chains

- packages/core/src/LinkedList.js
Remove straggler promise usage in LinkedList.
> Remove leftover promise usage in mergeConcurrently list

- docs/concepts.rst
- docs/index.rst
We've seen folks using most/core in ways where it may not be a good fit, such as time series data processing.  I figured I'd start the discussion about how to make a short statement up front in the docs that might be helpful.
> Add hints about when and when not to use most/core

- examples/package-lock.json
- examples/package.json
Update examples to use 1.0. Update devdeps
> Update example deps and devdeps

- packages/scheduler/rollup.config.js
> Fix umd name in most/scheduler build

- docs/api.rst
- packages/core/src/source/periodic.js
> Link and expand time types docs

- packages/core/src/combinator/loop.js
- packages/core/test/combinator/loop-test.js
> Return canonical empty in loop()

- packages/core/src/combinator/zip.js
- packages/core/src/source/empty.js
- packages/core/test/source/empty-test.js
- packages/core/test/zip-test.js
> Return canonical empty in zip, zipArray

- packages/core/src/combinator/combine.js
- packages/core/test/combine-test.js
> Return canonical empty in combine, combineArray

- packages/core/src/combinator/merge.js
- packages/core/test/combinator/merge-test.js
> Filter out canonical empty from merge, mergeArray

- packages/core/src/fusion/Map.js
- packages/core/test/transform-test.js
Close #178
Reference #152 
Signed-off-by: Frederik Krautwald <fkrautwald@gmail.com>
> Map return canonical empty

- packages/core/src/fusion/Filter.js
- packages/core/test/filter-test.js
Close #180
Reference #150, #152
Signed-off-by: Frederik Krautwald <fkrautwald@gmail.com>
> Filter return canonical empty

- packages/core/src/combinator/errors.js
- packages/core/test/combinator/errors-test.js
> Return canonical empty in recoverWith

- packages/core/src/combinator/applicative.js
- packages/core/test/combinator/applicative-test.js
Close #182
Reference #150, #152
Signed-off-by: Frederik Krautwald <fkrautwald@gmail.com>
> Applicative return canonical empty

- packages/core/src/combinator/filter.js
- packages/core/test/filter-test.js
> Return canonical empty in skipRepeats and skipRepeatsWith

- packages/core/src/combinator/multicast.js
- packages/core/test/combinator/multicast-test.js
> Make multicast return canonical empty

- packages/core/src/combinator/mergeConcurrently.js
- packages/core/test/combinator/mergeConcurrently-test.js
> Return canonical empty in mergeMapConcurrently

- packages/core/src/combinator/switch.js
- packages/core/test/switch-test.js
> make switchLatest return canonical empty

- packages/core/src/combinator/promises.js
- packages/core/test/combinator/promises-test.js
> make awaitPromises return canonical empty

- packages/core/src/combinator/slice.js
- packages/core/test/slice-test.js
> Return canonical empty in takeWhile, skipWhile, and skipAfter

- packages/core/src/combinator/limit.js
- packages/core/test/limit-test.js
> Make throttle and debounce return canonical empty

- packages/core/src/combinator/limit.js
- packages/core/test/limit-test.js
Post debounce fix from cujojs/most#515
See also https://github.com/cujojs/most/issues/514
> Port debounce fix from cujojs/most#515

- docs/adrs/TEMPLATE.md
Add an ADR template, based on #211.
> Add ADR template

- packages/core/src/combinator/delay.js
- packages/core/test/delay-test.js
Init PR based on our slack conversation, addresses the bug described in #243
> fix(delay) fixes the cancelAll predicate within DelaySink dispose

- docs/faq.rst
Questions about mostjs event streams and Node streams come up occasionally.  The fact that the two happened to use the same word, "stream", can be confusing for some folks.  Hopefully, adding some FAQ entries will help.  Here's one to start.
> Add Node streams FAQ

- examples/package-lock.json
- packages/core/test/perf/package-lock.json
- packages/core/test/perf/package.json
Good to do this periodically.  It updated a few things.
> Run npm audit fix

- packages/core/type-definitions/combinator/variadic.d.ts
> Add Stream import

- README.md
Followup to #386 and our switch to CircleCI.
> Add CircleCI badge, remove Travis badge

- packages/core/src/combinator/timeslice.ts
- packages/core/src/runEffects.ts
- packages/core/test/combinator/errors-test.ts
- packages/core/test/index-test.ts
- packages/types/index.d.ts
> feat: improve typesafety of Stream<A> interface

- .readthedocs.yaml
See: https://docs.readthedocs.io/en/stable/config-file/index.html
> Add required .readthedocs.yaml config
